[package]
authors = [
    "a |> louise <email@aloui.se>"
]
edition = "2018"
name = "led-roulette"
version = "0.1.0"

[dependencies]
cortex-m = "0.7.2"
cortex-m-rt = "0.6.14"
stm32f3-discovery = "0.7.0"
panic-itm = "0.4.2"
